### ISSUE TITLE
Admiral TryOut

### ISSUE THREAD

**Issue by dud3** [dud3/ADMIRAL#5]
# Description

I just lunched the half version of Admiral, feel free to use it, all you have to do is, just to register urself to the application.

<b>Link:</b> http://46.149.18.88/ADMIRAL/
## Usage

Just register, after that you have your:
- Workspace - where your files are uploaded
- SSH client - direct access to the <b>dev2</b> server, where you can explore everything, but edit nothing, outside ur folder
- MySQL client - Play with databases
- FTP Client - Not working yet, if you want to code, use SSH client(at least for now).
## Note

Only the FTP client won't work for now everything else is working pretty good.
BTW: You only have 5MB of space, at least for now...

**Comment by dud32** [comment]
OK :D>.
